/**
 * JavaScript Symbol Page
 *
 * Dynamic route handler for JavaScript/TypeScript package and symbol pages.
 * Parses the URL slug and renders the appropriate component.
 *
 * This page is statically generated at build time using generateStaticParams.
 */

import { notFound } from "next/navigation";
import { parseSlugWithLanguage } from "@/lib/utils/url";
import { SymbolPage } from "@/components/reference/SymbolPage";
import { PackagePage } from "@/components/reference/PackagePage";
import { getStaticParamsForLanguage } from "@/lib/ir/loader";
import { getEnabledProjects } from "@/lib/config/projects";

interface Props {
  params: Promise<{
    slug: string[];
  }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

/**
 * Generate static params for all JavaScript packages and symbols.
 * This enables static generation (SSG) for all pages at build time.
 * Generates params for ALL enabled projects (langchain, langgraph, deepagent).
 */
export async function generateStaticParams(): Promise<{ slug: string[] }[]> {
  const projects = getEnabledProjects();
  const allParams: { slug: string[] }[] = [];

  // Generate params for all projects in parallel
  const projectParams = await Promise.all(
    projects.map((project) => getStaticParamsForLanguage("javascript", project.id))
  );

  for (const params of projectParams) {
    allParams.push(...params);
  }

  return allParams;
}

/**
 * NOTE:
 * We intentionally do NOT force static rendering here.
 *
 * This route supports version switching via the `?v=` query param, which must
 * be able to change the rendered output on navigation. Forcing static rendering
 * would cause the URL to change while the view remains "latest".
 *
 * Pages generated by `generateStaticParams` are still pre-rendered, and we keep
 * ISR enabled via `revalidate`.
 */

/**
 * Enable Incremental Static Regeneration (ISR).
 * Pre-rendered pages are revalidated every hour.
 */
export const revalidate = 3600; // 1 hour

/**
 * Enable dynamic params for on-demand page generation.
 * Pages not in generateStaticParams (methods, properties, modules) are generated
 * on first request and cached.
 */
export const dynamicParams = true;

export default async function JavaScriptSymbolPage({ params, searchParams }: Props) {
  const { slug } = await params;
  const resolvedSearchParams = await searchParams;

  if (!slug || slug.length === 0) {
    notFound();
  }

  // Parse the slug - treat as JavaScript (includes TypeScript)
  const parsed = parseSlugWithLanguage(slug, "javascript");

  if (!parsed) {
    notFound();
  }

  // Get version from search params (e.g., ?v=1.1.6)
  const version = typeof resolvedSearchParams.v === "string" ? resolvedSearchParams.v : undefined;

  // If only package name, show package overview
  if (parsed.symbolPath.length === 0) {
    return (
      <PackagePage
        language="javascript"
        packageId={parsed.packageId}
        packageName={parsed.packageName}
      />
    );
  }

  // Otherwise, show symbol page
  return (
    <SymbolPage
      language="javascript"
      packageId={parsed.packageId}
      packageName={parsed.packageName}
      symbolPath={parsed.fullPath}
      version={version}
    />
  );
}

/**
 * Generate metadata for the page
 */
export async function generateMetadata({ params }: Props) {
  const { slug } = await params;
  const parsed = parseSlugWithLanguage(slug || [], "javascript");

  if (!parsed) {
    return { title: "Not Found" };
  }

  const symbolName = parsed.symbolPath.length > 0
    ? parsed.symbolPath[parsed.symbolPath.length - 1]
    : parsed.packageName;

  const title = `${symbolName} | ${parsed.packageName}`;
  const description = parsed.fullPath
    ? `JavaScript/TypeScript API reference for ${parsed.fullPath} in ${parsed.packageName}. Part of the LangChain ecosystem.`
    : `JavaScript/TypeScript API reference for ${parsed.packageName}. Part of the LangChain ecosystem.`;

  // Build OG image URL
  const ogImagePath = `/og/javascript/${slug.join("/")}`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      url: `/javascript/${slug.join("/")}`,
      images: [
        {
          url: ogImagePath,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImagePath],
    },
    alternates: {
      canonical: `/javascript/${slug.join("/")}`,
    },
  };
}



